spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://cafe.cueseswhafyp.ap-northeast-2.rds.amazonaws.com:3306/cafein
    username: root
    password: cafein1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profiles:
    include:
      - credential
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8080

cloud:
  aws:
    credentials:
      instance-profile: true
    region:
      static: ap-northeast-2
    s3:
      bucket: cafein
    stack:
      auto: false
